name: hack_ujin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.4.3+1
  hive_flutter: ^1.1.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  crypto: ^3.0.3
  flutter_charts: ^0.5.2

dev_dependencies: 
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.8.0

flutter: 
  uses-material-design: true
  assets: 
    - images/logos/